export const queryKeys = {
  currentUser: ['currentUser'] as const,
  feed: ['feed'] as const,
  post: (id: string) => ['post', id] as const,
  replies: (parentId: string) => ['replies', parentId] as const,
  profile: (username: string) => ['profile', username] as const,
  userPosts: (username: string) => ['userPosts', username] as const,
  userReplies: (username: string) => ['userReplies', username] as const,
  myLikedPosts: ['myLikedPosts'] as const,
  search: (q: string) => ['search', q] as const,
  notifications: ['notifications'] as const,
  hasNewNotification: ['hasNewNotification'] as const,
  suggestedUsers: (userId: string) => ['suggestedUsers', userId] as const,
  savedPosts: ['savedPosts'] as const,
  blockedUsers: ['blockedUsers'] as const,
  followRequests: ['followRequests'] as const,
  graphView: (userId: string) => ['graphView', userId] as const,
  nodeDetails: (userId: string) => ['nodeDetails', userId] as const,
};
